export const FETCH_DATA = 'fetch_users';
export const STORE_EDITED = 'STORE_EDITED';

export const NOT_AUTHORIZED_ERROR = 'NOT_AUTHORIZED_ERROR';
export const NOT_FOUND_ERROR = 'NOT_FOUND_ERROR';
export const INVALID_ROUTE_URL = 'INVALID_ROUTE_URL';
export const SERVER_DB_CONNECTION_ERROR = 'SERVER_DB_CONNECTION_ERROR';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
